import '../domain/solar_repository.dart';
import '../domain/models/basic_info.dart';
import '../domain/models/property_info.dart';
import '../domain/models/solar_proposal.dart';
import '../domain/models/uploaded_document.dart';
import '../domain/models/agreement.dart';
import '../domain/models/property_photo.dart';
import '../domain/models/inspection_schedule.dart';
import '../domain/models/solar_onboarding_state.dart';
import '../../../core/config/constants.dart';

class MockSolarRepository implements SolarRepository {
  @override
  Future<SolarProposal> generateProposal({
    required BasicInfo basicInfo,
    required PropertyInfo propertyInfo,
    required SystemType systemType,
  }) async {
    await Future.delayed(AppConstants.mockDelay);

    final sizeKw = propertyInfo.roofSizeSqFt / 200;
    final numberOfPanels = (sizeKw / 0.4).round();
    final annualProduction = sizeKw * 1400;
    final monthlySavings = annualProduction / 12 * 0.12;
    final totalCost = sizeKw * 2800;
    final monthlyPayment = totalCost / (20 * 12);

    return SolarProposal(
      systemSizeKw: sizeKw,
      numberOfPanels: numberOfPanels,
      estimatedAnnualProductionKwh: annualProduction,
      monthlySavings: monthlySavings,
      totalCost: totalCost,
      monthlyPayment: monthlyPayment,
      coverageYears: 20,
    );
  }

  @override
  Future<CreditStatus> checkCredit({required String userId}) async {
    await Future.delayed(AppConstants.mockDelay);
    return CreditStatus.approved;
  }

  @override
  Future<List<Agreement>> getAgreements() async {
    await Future.delayed(AppConstants.mockDelay);
    return const [
      Agreement(
        id: 'agreement-1',
        title: 'Solar Installation Agreement',
        content:
            'This Solar Installation Agreement ("Agreement") is entered into by and '
            'between Ancestro Energy LLC ("Company") and the homeowner ("Customer"). '
            'The Company agrees to install a solar photovoltaic system at the '
            'Customer\'s property in accordance with the proposal provided. '
            'Installation will be performed by licensed professionals and will comply '
            'with all local building codes and regulations. The Customer grants the '
            'Company access to the property for installation and maintenance purposes. '
            'This Agreement is valid for a period of 20 years from the date of system '
            'activation.',
      ),
      Agreement(
        id: 'agreement-2',
        title: 'Power Purchase Agreement (PPA)',
        content:
            'This Power Purchase Agreement ("PPA") outlines the terms under which '
            'the Customer will purchase electricity generated by the solar system. '
            'The Customer agrees to purchase all electricity produced by the system at '
            'a fixed rate per kilowatt-hour. The rate will escalate by 2.9% annually. '
            'The Company will maintain ownership of the system and is responsible for '
            'all maintenance and repairs. Net metering credits will be allocated to the '
            'Customer\'s utility account.',
      ),
      Agreement(
        id: 'agreement-3',
        title: 'Warranty & Maintenance Agreement',
        content:
            'This Warranty & Maintenance Agreement covers the solar photovoltaic '
            'system installed at the Customer\'s property. The Company provides a 25-year '
            'performance warranty guaranteeing at least 80% of original production '
            'capacity. The panels carry a manufacturer warranty of 25 years. Inverters '
            'are covered for 12 years with the option to extend. The Company will '
            'perform annual inspections and maintenance at no additional cost for the '
            'first 10 years of the agreement.',
      ),
    ];
  }

  @override
  Future<void> submitDocuments({
    required String userId,
    required List<UploadedDocument> documents,
  }) async {
    await Future.delayed(AppConstants.mockDelay);
  }

  @override
  Future<void> submitPropertyPhotos({
    required String userId,
    required List<PropertyPhoto> photos,
  }) async {
    await Future.delayed(AppConstants.mockDelay);
  }

  @override
  Future<bool> reviewPropertyPhotos({
    required String userId,
    required List<PropertyPhoto> photos,
  }) async {
    await Future.delayed(AppConstants.mockDelay);
    return true;
  }

  @override
  Future<List<DateTime>> getAvailableInspectionDates() async {
    await Future.delayed(AppConstants.mockDelay);
    final now = DateTime.now();
    return List.generate(
      14,
      (i) => DateTime(now.year, now.month, now.day + i + 1),
    );
  }

  @override
  Future<InspectionSchedule> scheduleInspection({
    required String userId,
    required DateTime date,
    required String timeSlot,
  }) async {
    await Future.delayed(AppConstants.mockDelay);
    return InspectionSchedule(
      date: date,
      timeSlot: timeSlot,
      inspectorName: 'Carlos Rivera',
      inspectorPhone: '(555) 123-4567',
    );
  }

  @override
  Future<void> completeOnboarding({required String userId}) async {
    await Future.delayed(AppConstants.mockDelay);
  }
}
